# Generated by Django 4.1.7 on 2023-04-22 00:52

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('female', 'Mujer'), ('male', 'Hombre'), ('other', 'Otro')], max_length=10)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Climb_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_climb', models.DateField()),
                ('place_name', models.CharField(max_length=40)),
                ('place_coord', models.CharField(max_length=30)),
                ('enviroment', models.CharField(max_length=20)),
                ('climb_style', models.CharField(max_length=15)),
                ('multipitches', models.BooleanField()),
                ('num_pitches', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(15)])),
                ('grade', models.CharField(max_length=6)),
                ('climber_position', models.CharField(max_length=15)),
                ('ascent_type', models.CharField(max_length=20)),
                ('num_attempts', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(max_length=400)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='climb_log_webapp.user')),
            ],
            options={
                'ordering': ['date_of_entry'],
            },
        ),
    ]
