# Generated by Django 4.2.2 on 2023-07-20 18:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('place_coords', models.CharField(max_length=50)),
                ('enviroment', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClimbEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_climb', models.DateField()),
                ('climb_style', models.CharField(max_length=15)),
                ('multipitches', models.BooleanField()),
                ('num_pitches', models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(15)])),
                ('grade', models.CharField(max_length=20)),
                ('grade_equivalent', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(15)])),
                ('climber_position', models.CharField(blank=True, default='lead', max_length=15, null=True)),
                ('ascent_type', models.CharField(max_length=20)),
                ('num_attempts', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True, default='No hay notas', max_length=400)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('place_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climb_log_webapp.climbplaces')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_of_climb'],
            },
        ),
    ]
