# Generated by Django 4.2.2 on 2023-07-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbentry',
            name='num_attempts',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
