# Generated by Django 4.1.7 on 2023-04-08 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climb_entry',
            old_name='user_id',
            new_name='entry_num',
        ),
        migrations.AddField(
            model_name='climb_entry',
            name='username',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='climb_log_webapp.users'),
            preserve_default=False,
        ),
    ]
