# Generated by Django 4.1.7 on 2023-04-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0002_alter_climb_entry_username_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb_entry',
            name='grade',
            field=models.CharField(max_length=20),
        ),
    ]
