# Generated by Django 4.1.7 on 2023-04-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0002_rename_user_id_climb_entry_entry_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb_entry',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='climb_log_webapp.users'),
        ),
    ]
