# Generated by Django 4.2.2 on 2023-07-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0002_alter_climbentry_num_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbentry',
            name='ascent_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
