# Generated by Django 4.1.7 on 2023-04-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0003_alter_climb_entry_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb_entry',
            name='place_coord',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
