# Generated by Django 4.1.7 on 2023-04-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0003_alter_climb_entry_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='climb_entry',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='climb_entry',
            name='entry_num',
            field=models.CharField(max_length=20),
        ),
    ]
