# Generated by Django 4.2.2 on 2023-07-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0004_alter_climbentry_ascent_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbentry',
            name='notes',
            field=models.TextField(blank=True, default='No hay notas', max_length=400, null=True),
        ),
    ]
