# Generated by Django 4.1.7 on 2023-04-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0004_climb_entry_id_alter_climb_entry_entry_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climb_entry',
            name='id',
        ),
        migrations.AlterField(
            model_name='climb_entry',
            name='entry_num',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
