# Generated by Django 4.2.2 on 2023-07-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0005_alter_climbentry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbentry',
            name='place_name',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='climb_log_webapp.climbplaces'),
            preserve_default=False,
        ),
    ]
