# Generated by Django 4.1.7 on 2023-05-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0005_alter_climb_entry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb_entry',
            name='notes',
            field=models.TextField(default='No hay notas', max_length=400),
        ),
    ]
