# Generated by Django 4.1.7 on 2023-04-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0006_users_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='id',
        ),
    ]
