# Generated by Django 4.2.2 on 2023-07-24 00:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('climb_log_webapp', '0006_alter_climbentry_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbplaces',
            name='place_coords',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='climbplaces',
            name='place_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, default='unknown', max_length=15, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(110)])),
                ('nationality', models.CharField(blank=True, default='Citizen of the World', max_length=15, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile-icon.png', null=True, upload_to='')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
