# Generated by Django 4.1.7 on 2023-04-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0007_rename_user_id_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('female', 'Mujer'), ('male', 'Hombre'), ('other', 'Otro')], max_length=10),
        ),
    ]
