# Generated by Django 4.1.7 on 2023-05-27 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0007_alter_climb_entry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb_entry',
            name='num_pitches',
            field=models.PositiveSmallIntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(15)]),
        ),
    ]
