# Generated by Django 4.2.2 on 2023-07-16 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0010_alter_climb_entry_climber_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='climb_entry',
            name='grade_equivalent',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(15)]),
        ),
    ]
