# Generated by Django 4.1.7 on 2023-04-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0011_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb_entry',
            name='entry_num',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
