# Generated by Django 4.2.2 on 2023-07-16 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_log_webapp', '0011_climb_entry_grade_equivalent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb_entry',
            name='grade_equivalent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(15)]),
        ),
    ]
